release: "github"
github:
  repo: "go-semantic-release"
  user: "nightapes"
commitFormat: angular
branch:
  master: release
  beta: beta
assets:
  - name: ./build/go-semantic-release.linux_x86_64
    compress: true
  - name: ./build/go-semantic-release.windows_i386.exe
    compress: true
  - name: ./build/go-semantic-release.windows_x86_64.exe
    compress: true
  - name: ./build/go-semantic-release.darwin_x86_64
    compress: true
changelog:
  docker:
    latest: true
    repository: "nightapes/go-semantic-release"
hooks:
  preRelease:
    - docker build -t nightapes/go-semantic-release:latest .
    - docker tag nightapes/go-semantic-release:latest docker.pkg.github.com/nightapes/go-semantic-release/go-semantic-release:$RELEASE_VERSION
    - docker tag nightapes/go-semantic-release:latest nightapes/go-semantic-release:$RELEASE_VERSION
  postRelease:
    - docker push nightapes/go-semantic-release:latest
    - docker push nightapes/go-semantic-release:$RELEASE_VERSION
    - docker push docker.pkg.github.com/nightapes/go-semantic-release/go-semantic-release:$RELEASE_VERSION
